# Generated by Django 2.1.1 on 2020-02-02 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20200130_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator])),
                ('expense', models.IntegerField(validators=[django.core.validators.MinValueValidator])),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='products.Product')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
