# Generated by Django 2.1.1 on 2020-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200203_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='first published date'),
        ),
    ]
